[connections.supabase]
url = "https://uogvogfyzvizpcdiwoqe.supabase.co"
key ="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVvZ3ZvZ2Z5enZpenBjZGl3b3FlIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2Mjc5OTQ5MiwiZXhwIjoyMDc4Mzc1NDkyfQ.Ou3DvH8rRx1wMlujY-DHlGdycvc2i1F2N3yUlPVjQe8"